### ISSUE TITLE
Error & packets

### ISSUE THREAD

**Issue by vicochips** [JoeAlisson/L2jOrg#114]
- [ ] [WARN ][2020-04-14 16:01:08][ClientPacketHandler:unknownPacket:54]: Unknown Packet (REQUEST_USER_BAN_INFO) : d0 - 00000000 D05E0129840000                   .^.)...

- [ ] [WARN ][2020-04-14 16:01:17][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_REQUEST_CLASS_CHANGE_VERIFYING) : d0 - 00000000 D066015E000000                   .f.^...

- [x] `[java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:222)
        at java.base/java.util.concurrent.ConcurrentLinkedQueue.offer(ConcurrentLinkedQueue.java:355)
        at java.base/java.util.concurrent.ConcurrentLinkedQueue.add(ConcurrentLinkedQueue.java:283)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.close(Client.java:138)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.close(Client.java:123)
        at org.l2j.gameserver/org.l2j.gameserver.network.authcomm.AuthServerCommunication.shutdown(AuthServerCommunication.java:107)
        at org.l2j.gameserver/org.l2j.gameserver.Shutdown.saveDataAndReleaseResources(Shutdown.java:109)
        at org.l2j.gameserver/org.l2j.gameserver.Shutdown.run(Shutdown.java:73)
`

**Comment by vicochips** [comment]
- [ ] `
[ERROR][2020-04-14 18:18:27][ClientPacket:run:38]: [Classic - Kamael: 1.4.0-72050f4 (2020-04-14T17:31:20.601+0200)] Error while running packet org.l2j.gameserver.network.clientpackets.Logout@2573848e from client [Player: disconnected - Account: imrik - IP: ]
[ERROR][2020-04-14 18:18:27][ClientPacket:run:39]: null
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:222)
        at java.base/java.util.concurrent.ConcurrentLinkedQueue.offer(ConcurrentLinkedQueue.java:355)
        at java.base/java.util.concurrent.ConcurrentLinkedQueue.add(ConcurrentLinkedQueue.java:283)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.close(Client.java:138)
        at org.l2j.gameserver/org.l2j.gameserver.network.GameClient.closeNow(GameClient.java:237)
        at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.Logout.runImpl(Logout.java:28)
        at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
        at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$1.run(PriorityThreadFactory.java:35)
`

**Comment by vicochips** [comment]
- [ ] [WARN ][2020-04-15 09:46:19][ClientPacketHandler:unknownPacket:54]: Unknown Packet (org.l2j.gameserver.network.PacketFactory$$Lambda$1310/0x00000008012a5040@6ea8828a) : d0 - 00000000 D0950100                         ....

**Comment by vicochips** [comment]
- [ ] [WARN ][2020-04-16 16:26:03][ClientPacketHandler:makePacketWithFactory:47]: Client [Player: Imrik[33833] - Account: imrik - IP: 127.0.0.1] sent packet REQUEST_KEY_MAPPING at invalid state IN_GAME Required States: [JOINING_GAME] - [d0]: 00000000 D02100

**Comment by vicochips** [comment]
Error: Assertion failed: Delta==Delta [File:UnPhysic.cpp] [Line: 1297]

Protocol: S_USER_INFO(35, 1) <= S_EX_TIME_RESTRICT_FIELD_USER_E(5, 1) <= S_EX_SET_COMPASS_ZONE_CODE(9, 1) <= S_NPC_INFO(82, 1) <= S_NPC_INFO(82, 1) <= S_NPC_INFO(82, 1) <= S_NPC_INFO(94, 1) <= S_NPC_INFO(79, 1) <= S_NPC_INFO(94, 1) <= S_NPC_INFO(94, 1)

History: APawn::physWalking <+ monster_eye Transient.monster_eye Loc.X=1040.000000 Y=178413.000000 Z=-3821.000000 Acc.X0.000000 Y=0.000000 Z=0.000000 Vel.X=-1.#IND00 Y=-1.#IND00 Z=-1.#IND00 Delta.X=-1.#IND00 Y=-1.#IND00 Z=0.000000 <- APawn::performPhysics <- AActor::Tick <+ Transient.monster_eye <- TickAllActors <- ULevel::Tick <+ (NetMode=0) <- UMasterLevel::Tick <- TickLevel <- UGameEngine::Tick <- UpdateWorld <- CMainLoop::UpdateTheWorld <- MainLoop
