### ISSUE TITLE
Erros em Packets

### ISSUE THREAD

**Issue by spiteridiick** [JoeAlisson/L2jOrg#117]
- [ ] ERRO NO BUFFER DA CB
```
[WARN ][2020-04-15 01:23:33][RequestBypassToServer:runImpl:225]: Exception processing bypass from player admin: _bbsbuff;1191,3;buffer/resist_list
java.lang.NullPointerException
	at org.l2j.scripts/handlers.communityboard.HomeBoard.parseCommunityBoardCommand(HomeBoard.java:224)
	at org.l2j.gameserver/org.l2j.gameserver.handler.CommunityBoardHandler.handleParseCommand(CommunityBoardHandler.java:108)
	at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.RequestBypassToServer.runImpl(RequestBypassToServer.java:121)
	at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:36)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$1.run(PriorityThreadFactory.java:35)

```

- [x] ERROS DE PACKET

```
 [WARN ][2020-04-15 02:09:51][ClientPacketHandler:unknownPacket:54]: Unknown Packet (REQUEST_USER_BAN_INFO) : d0 - 00000000 D05E01C8800000                   .^.....
 [WARN ][2020-04-15 02:10:04][Creature:setAccessLevel:246]: Master access level set for player Player:admin[32968] ! Just a warning to be careful ;)
[WARN ][2020-04-15 02:11:03][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_REQUEST_CLASS_CHANGE_VERIFYING) : d0 - 00000000 D06601C0000000                   .f.....
```

- [ ] ERROS DE QUEST INICIAL... EM TODAS AS RAÇAS, QUANDO VAI PEGAR A QUEST NO LVL 20
```

[WARN ][2020-04-15 02:17:54][RequestBypassToServer:runImpl:225]: Exception processing bypass from player admin: npc_6345_Quest
java.lang.NullPointerException
	at org.l2j.scripts/quests.Q10964_SecretGarden.Q10964_SecretGarden.onTalk(Q10964_SecretGarden.java:158)
	at org.l2j.gameserver/org.l2j.gameserver.model.quest.Quest.onTalk(Quest.java:1145)
	at org.l2j.scripts/handlers.bypasshandlers.QuestLink.lambda$showQuestWindow$1(QuestLink.java:236)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.concurrent.PriorityBlockingQueue$PBQSpliterator.forEachRemaining(PriorityBlockingQueue.java:979)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.l2j.scripts/handlers.bypasshandlers.QuestLink.showQuestWindow(QuestLink.java:238)
	at org.l2j.scripts/handlers.bypasshandlers.QuestLink.useBypass(QuestLink.java:43)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.Npc.onBypassFeedback(Npc.java:500)
	at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.RequestBypassToServer.runImpl(RequestBypassToServer.java:137)
	at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:36)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$1.run(PriorityThreadFactory.java:35)

```
```
[WARN ][2020-04-15 02:18:03][RequestBypassToServer:runImpl:225]: Exception processing bypass from player admin: npc_6345_Quest
java.lang.NullPointerException
	at org.l2j.scripts/quests.Q10964_SecretGarden.Q10964_SecretGarden.onTalk(Q10964_SecretGarden.java:158)
	at org.l2j.gameserver/org.l2j.gameserver.model.quest.Quest.onTalk(Quest.java:1145)
	at org.l2j.scripts/handlers.bypasshandlers.QuestLink.lambda$showQuestWindow$1(QuestLink.java:236)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.concurrent.PriorityBlockingQueue$PBQSpliterator.forEachRemaining(PriorityBlockingQueue.java:979)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.l2j.scripts/handlers.bypasshandlers.QuestLink.showQuestWindow(QuestLink.java:238)
	at org.l2j.scripts/handlers.bypasshandlers.QuestLink.useBypass(QuestLink.java:43)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.Npc.onBypassFeedback(Npc.java:500)
	at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.RequestBypassToServer.runImpl(RequestBypassToServer.java:137)
	at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:36)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$1.run(PriorityThreadFactory.java:35)
[WARN ][2020-04-15 02:19:21][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_REQUEST_CLASS_CHANGE_VERIFYING) : d0 - 00000000 D06601C0000000                   .f.....
[WARN ][2020-04-15 02:19:25][ClientPacketHandler:unknownPacket:54]: Unknown Packet (EX_REQUEST_CLASS_CHANGE_VERIFYING) : d0 - 00000000 D0660107000000                   .f.....

```

- [ ]  ESTÁ DANDO ERRO NO AUTO PLAY TAMBEM

**Comment by JoeAlisson** [comment]
Qual o erro do Auto play ?

**Comment by spiteridiick** [comment]
Não tá funcionando. Liga ele e ele não funciona

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by JoeAlisson** [comment]
Você precisa ativar alguma skill ou ação. coloca alguma skill que tenha o símbolo do auto play e ativa com o botão direito
