### ISSUE TITLE
Error gameserver and can't login

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#119]
[ERROR][2020-04-17 01:50:13][ClientPacket:run:38]: [Classic - Kamael: 1.4.0- (2020-04-17T01:34:45.524+0700)] Error while running packet org.l2j.gameserver.network.clientpackets.CharacterSelect@48db5fde from client [Account: gsinv - IP: 127.0.0.1]
[ERROR][2020-04-17 01:50:13][ClientPacket:run:39]: null
java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy62.findCostumes(Unknown Source)
        at org.l2j.gameserver/org.l2j.gameserver.model.actor.instance.Player.restore(Player.java:1049)
        at org.l2j.gameserver/org.l2j.gameserver.model.actor.instance.Player.load(Player.java:1026)
        at org.l2j.gameserver/org.l2j.gameserver.network.GameClient.load(GameClient.java:416)
        at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.CharacterSelect.runImpl(CharacterSelect.java:100)
        at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
        at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$1.run(PriorityThreadFactory.java:35)
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'locked' in 'field list'
        at mysql.connector.java@8.0.19/com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at mysql.connector.java@8.0.19/com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at mysql.connector.java@8.0.19/com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at mysql.connector.java@8.0.19/com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at mysql.connector.java@8.0.19/com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
        at com.zaxxer.hikari@3.4.2/com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari@3.4.2/com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at org.l2j.commons/org.l2j.commons.database.helpers.QueryDescriptor.execute(QueryDescriptor.java:73)
        at org.l2j.commons/org.l2j.commons.database.JDBCInvocation.invoke(JDBCInvocation.java:70)
        ... 10 more

**Comment by JoeAlisson** [comment]
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'locked' in 'field list'

Update your player_costumes table on DB
