### ISSUE TITLE
Erros de Level e Skill

### ISSUE THREAD

**Issue by spiteridiick** [JoeAlisson/L2jOrg#133]
Este erro está dando quando mata algum mob.
[ERROR][2020-04-20 13:01:29][Creature:calculateRewards:529]: 
java.lang.NullPointerException
	at org.l2j.gameserver/org.l2j.gameserver.data.xml.impl.LevelData.getExpForLevel(LevelData.java:58)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.stat.PlayerStats.getExpForLevel(PlayerStats.java:254)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.stat.PlayableStats.addExp(PlayableStats.java:37)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.stat.PlayerStats.addExp(PlayerStats.java:57)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.stat.PlayerStats.addExpAndSp(PlayerStats.java:133)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.instance.Player.addExpAndSp(Player.java:8416)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.Attackable.calculateRewards(Attackable.java:428)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.Creature.doDie(Creature.java:1314)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.Npc.doDie(Npc.java:749)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.Attackable.doDie(Attackable.java:248)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.instance.Monster.doDie(Monster.java:112)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.status.CharStatus.reduceHp(CharStatus.java:146)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.status.NpcStatus.reduceHp(NpcStatus.java:34)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.status.AttackableStatus.reduceHp(AttackableStatus.java:32)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.Creature.reduceCurrentHp(Creature.java:3706)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.Attackable.reduceCurrentHp(Attackable.java:224)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.Creature.doAttack(Creature.java:3590)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.Creature.onHitTarget(Creature.java:3072)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.Creature.onFirstHitTimeForDual(Creature.java:3042)
	at org.l2j.gameserver/org.l2j.gameserver.model.actor.Creature.lambda$doAutoAttack$8(Creature.java:919)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$1.run(PriorityThreadFactory.java:35)

**Comment by JoeAlisson** [comment]
Qual o level do player ?

**Comment by spiteridiick** [comment]
Lvl 0, mas resolvi o problema, o problema e que no level-data tinha colocado lvl Max 90, e quando coloca essa config da esse erro agora quando volta lvl 85 volta ao normal. Acho que no Java tem que colocar pra poder upar até o lvl 90

Obter o Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by JoeAlisson** [comment]
Para ir até o level 90, é necessário adicionar o level 91 em level-data.xml. Por exemplo:
`<level-data level="91" experience="90699183112788" characteristic-points="15" />

Mas ainda não suportamos oficialmente o level 90, que deverá ocorrer após o próximo update

**Comment by xcelebration** [comment]
kamael is max lv 85?
