### ISSUE TITLE
Can't login after upgrade earth spirit to level 4

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#138]
Human class id 88
[ERROR][2020-04-21 22:49:19][Client:write:99]: null
java.nio.BufferOverflowException
        at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:458)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Connection.write(Connection.java:50)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.encryptAndWrite(Client.java:113)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.write(Client.java:97)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.tryWriteNextPacket(Client.java:74)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.writePacket(Client.java:60)
        at org.l2j.gameserver/org.l2j.gameserver.network.GameClient.sendPacket(GameClient.java:304)
        at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.EnterWorld.runImpl(EnterWorld.java:137)
        at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
        at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$1.run(PriorityThreadFactory.java:35)

**Comment by JoeAlisson** [comment]
Did you change anything on async-mmocore.properties ?

Seems to be unrelated to elemental spirit given the error log, the server was sending the item list to client.

**Comment by bahamus20** [comment]
original async-mmocore.properties (nothing change)

**Comment by bahamus20** [comment]
l2.exe not respond
More information 
[ERROR][2020-04-22 09:50:18][Client:write:99]: null
java.nio.BufferOverflowException
        at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:458)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Connection.write(Connection.java:50)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.encryptAndWrite(Client.java:113)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.write(Client.java:97)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.tryWriteNextPacket(Client.java:74)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.writePacket(Client.java:60)
        at org.l2j.gameserver/org.l2j.gameserver.network.GameClient.sendPacket(GameClient.java:304)
        at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.EnterWorld.runImpl(EnterWorld.java:137)
        at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
        at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$1.run(PriorityThreadFactory.java:35)

After close l2.exe
[WARN ][2020-04-22 09:50:31][ReadHandler:failed:128]: The specified network name is no longer available
java.io.IOException: The specified network name is no longer available
        at java.base/sun.nio.ch.Iocp.translateErrorToIOException(Iocp.java:299)
        at java.base/sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:389)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by JoeAlisson** [comment]
Can you provide a dump of character's items from your db ?

**Comment by bahamus20** [comment]
Sorry I just clean database 
If finding the same problem Will report again

I think that might be a problem that some items are too many but not sure.
