### ISSUE TITLE
Error after click Ranking

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#194]
[ERROR][2020-05-15 08:38:29][ServerPacket:write:53]: [Classic - Kamael [Dawn of Heroes]: 1.5.0- (2020-05-15T08:11:45.152+0700)] Error writing packet ExRankList to client [Player: CLASSIC[33194] - Account: sssss - IP: 127.0.0.1]
[ERROR][2020-05-15 08:38:29][ServerPacket:write:54]: null
java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy69.findAll(Unknown Source)
        at org.l2j.gameserver/org.l2j.gameserver.data.database.RankManager.getRankers(RankManager.java:169)
        at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.rank.ExRankList.listServerRankers(ExRankList.java:68)
        at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.rank.ExRankList.writeImpl(ExRankList.java:38)
        at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.ServerPacket.write(ServerPacket.java:50)
        at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.ServerPacket.write(ServerPacket.java:19)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WritablePacket.writeData(WritablePacket.java:219)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.write(Client.java:83)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.tryWriteNextPacket(Client.java:75)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.finishWriting(Client.java:155)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.write(Client.java:86)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.tryWriteNextPacket(Client.java:75)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.sql.SQLSyntaxErrorException: Table 'l2jorg.rankers' doesn't exist
        at mysql.connector.java@8.0.19/com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at mysql.connector.java@8.0.19/com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at mysql.connector.java@8.0.19/com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at mysql.connector.java@8.0.19/com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at mysql.connector.java@8.0.19/com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
        at com.zaxxer.hikari@3.4.2/com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari@3.4.2/com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at org.l2j.commons/org.l2j.commons.database.helpers.QueryDescriptor.executeSingle(QueryDescriptor.java:123)
        at org.l2j.commons/org.l2j.commons.database.helpers.QueryDescriptor.execute(QueryDescriptor.java:96)
        at org.l2j.commons/org.l2j.commons.database.JDBCInvocation.invoke(JDBCInvocation.java:69)
        ... 19 more

**Comment by JoeAlisson** [comment]
`Caused by: java.sql.SQLSyntaxErrorException: Table 'l2jorg.rankers' doesn't exist`

Please, make sure thre is the view rankers in your database. You can find it on '1_characters.sql' file

**Comment by xcelebration** [comment]
need mysql 8 pls upgrade

**Comment by bahamus20** [comment]
Thank xcelebration

**Comment by bahamus20** [comment]
Fixed mysql
