### ISSUE TITLE
Erros

### ISSUE THREAD

**Issue by spiteridiick** [JoeAlisson/L2jOrg#200]
Após a nova att, a Comunity não está funcionando não abre e nem da erro nenhum no GS, simplesmente não abre e as skills que multiplicavam a XP estavam todas corretas agora estão dando erros por exemplo as skills passivas do VIP que davam 20/25/30/35% de XP agora estão aumentando 2000/2500/3000/3500 de XP.

**Comment by spiteridiick** [comment]
E Também dando esse erro nessa skill

[WARN ][2020-05-15 15:46:30][XmlReader:parseFile:101]: Could not parse file: 45100-45199.xml at line: 1106, column: 37 :
org.xml.sax.SAXParseException; systemId: file:/C:/Users/spite/IdeaProjects/L2jOrg/build/distributions/L2jOrg-1.5.1/gameserver/data/skills/45100-45199.xml; lineNumber: 1106; columnNumber: 37; cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://l2j.org":check-range}'. One of '{"http://l2j.org":cond}' is expected.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:511)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3587)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1971)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.emptyElement(XMLSchemaValidator.java:849)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:351)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2725)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:541)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:246)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:206)
	at org.l2j.commons/org.l2j.commons.xml.XmlReader.parseFile(XmlReader.java:98)
	at org.l2j.commons/org.l2j.commons.xml.XmlReader.parseDirectory(XmlReader.java:132)
	at org.l2j.gameserver/org.l2j.gameserver.util.GameXmlReader.parseDatapackDirectory(GameXmlReader.java:45)
	at org.l2j.gameserver/org.l2j.gameserver.engine.skill.api.SkillEngine.load(SkillEngine.java:94)
	at org.l2j.gameserver/org.l2j.gameserver.engine.skill.api.SkillEngine.init(SkillEngine.java:469)
	at org.l2j.gameserver/org.l2j.gameserver.GameServer.<init>(GameServer.java:81)
	at org.l2j.gameserver/org.l2j.gameserver.GameServer.main(GameServer.java:256)
