### ISSUE TITLE
Admin view Queen ant error

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#239]
After relogin game back to normal
[WARN ][2020-05-23 23:15:58][AdminCommandHandler:lambda$useAdminCommand$0:94]: Exception during execution of admin_grandboss 29028: java.lang.NullPointerException
[ERROR][2020-05-23 23:17:00][Client:write:100]: null
java.nio.BufferOverflowException
        at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:457)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Connection.write(Connection.java:50)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.encryptAndWrite(Client.java:114)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.write(Client.java:98)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.tryWriteNextPacket(Client.java:75)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
[ERROR][2020-05-23 23:17:02][Client:write:100]: null

![Shot00050](https://user-images.githubusercontent.com/63811728/82735538-aa645980-9d4c-11ea-943a-ae8e7795e666.jpg)

**Comment by bahamus20** [comment]
NpcView
Sometime error 
![EEEEEEEEEEEEEEEEE](https://user-images.githubusercontent.com/63811728/82735854-0e881d00-9d4f-11ea-8159-05ed75717c1f.png)

**Comment by JoeAlisson** [comment]
The view droplist need to be reworked to show drops in pages.
