### ISSUE TITLE
Question about the game server

### ISSUE THREAD

**Issue by expert43** [JoeAlisson/L2jOrg#250]
Some time after the launch, this message POPs up, perhaps several times, what does it mean? is this how it should be?

Exception in thread "pool-2-thread-4" java.lang.NullPointerException
        at java.base/java.util.concurrent.ConcurrentHashMap.replaceNode(ConcurrentHashMap.java:1111)
        at java.base/java.util.concurrent.ConcurrentHashMap.remove(ConcurrentHashMap.java:1102)
        at org.l2j.gameserver/org.l2j.gameserver.network.authcomm.AuthServerCommunication.removeWaitingClient(AuthServerCommunication.java:80)
        at org.l2j.gameserver/org.l2j.gameserver.network.GameClient.onDisconnection(GameClient.java:220)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.disconnect(Client.java:160)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.ReadHandler.completed(ReadHandler.java:36)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.ReadHandler.completed(ReadHandler.java:16)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:282)
        at java.base/sun.nio.ch.WindowsAsynchronousSocketChannelImpl$ReadTask.completed(WindowsAsynchronousSocketChannelImpl.java:581)
        at java.base/sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:387)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
.

**Comment by JoeAlisson** [comment]
It should no interfer on gameserver. The authserver is only trying to remove a client that no longer exists from queue. But need to be fixed
