### ISSUE TITLE
Error development no error on vicochipsdev

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#275]
\data\scripts\org.l2j.scripts\module-info.java 360:38

[WARN ][2020-06-03 12:11:15][PropertiesParser:getInt:130]: [althars.ini] missing property for key: althars_activation_chance_rate using default value: 70
[WARN ][2020-06-03 12:11:15][PropertiesParser:getInt:130]: [althars.ini] missing property for key: althars_max_active using default value: 3
[WARN ][2020-06-03 12:11:15][PropertiesParser:getInt:130]: [althars.ini] missing property for key: althars_min_duration_cycle using default value: 240000
[WARN ][2020-06-03 12:11:15][PropertiesParser:getInt:130]: [althars.ini] missing property for key: althars_max_duration_cycle using default value: 480000
[INFO ][2020-06-03 12:11:15][GameServer:printSection:314]: ------------------------------------------------=[ Scripting Engine ]
[INFO ][2020-06-03 12:11:15][ScriptEngineManager:registerEngine:67]: Java Engine 14 (Java [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
[WARN ][2020-06-03 12:11:16][JavaExecutionContext:report:222]: .\data\scripts\org.l2j.scripts\module-info.java 360:38 - cannot access ai.others.ClanHallMan
ager.ClanHallManager
  bad class file: compiledScripts\org.l2j.scripts\ai\others\ClanHallManager\ClanHallManager.class
    class file contains wrong class: ai.others.ClanHallDoorManager.ClanHallDoorManager
    Please remove or make sure it appears in the correct subdirectory of the classpath.
[WARN ][2020-06-03 12:11:17][JavaExecutionContext:report:222]: .\data\scripts\org.l2j.scripts\module-info.java -1:-1 - .\data\scripts\org.l2j.scripts\modul
e-info.java uses preview language features.
[WARN ][2020-06-03 12:11:17][JavaExecutionContext:report:222]: .\data\scripts\org.l2j.scripts\module-info.java -1:-1 - Recompile with -Xlint:preview for de
tails.
[ERROR][2020-06-03 12:11:17][JavaExecutionContext:<init>:58]: Could not compile Java Scripts
org.l2j.gameserver.engine.scripting.java.JavaCompilerException:
        at org.l2j.gameserver/org.l2j.gameserver.engine.scripting.java.JavaExecutionContext.compile(JavaExecutionContext.java:103)
        at org.l2j.gameserver/org.l2j.gameserver.engine.scripting.java.JavaExecutionContext.compileModuleInfo(JavaExecutionContext.java:70)
        at org.l2j.gameserver/org.l2j.gameserver.engine.scripting.java.JavaExecutionContext.<init>(JavaExecutionContext.java:55)
        at org.l2j.gameserver/org.l2j.gameserver.engine.scripting.java.JavaScriptingEngine.createExecutionContext(JavaScriptingEngine.java:45)
        at org.l2j.gameserver/org.l2j.gameserver.engine.scripting.ScriptEngineManager.registerEngine(ScriptEngineManager.java:68)
        at org.l2j.gameserver/org.l2j.gameserver.engine.scripting.ScriptEngineManager.lambda$loadEngines$0(ScriptEngineManager.java:52)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.l2j.gameserver/org.l2j.gameserver.engine.scripting.ScriptEngineManager.loadEngines(ScriptEngineManager.java:52)
        at org.l2j.gameserver/org.l2j.gameserver.engine.scripting.ScriptEngineManager.init(ScriptEngineManager.java:41)
        at org.l2j.gameserver/org.l2j.gameserver.GameServer.main(GameServer.java:246)
[WARN ][2020-06-03 12:11:17][JavaExecutionContext:report:224]: Some input files use preview language features.
[WARN ][2020-06-03 12:11:17][JavaExecutionContext:report:224]: Recompile with -Xlint:preview for details.

**Comment by vicochips** [comment]
Hello :),

Delete compiled script folder if you change branch etc :)

Then no more errors.

**Comment by bahamus20** [comment]
Thank
