### ISSUE TITLE
Error community board need to restart game (Game Crash)

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#302]
**### Gameserver Error**
[INFO ][2020-06-09 10:00:19][accounting:runImpl:119]: [Player: AA[39574] - Account: gsinv - IP: 124.122.238.178] Logged in
[WARN ][2020-06-09 10:01:54][RequestBypassToServer:runImpl:224]: Exception processing bypass from player AA: _bbsbuff 1323,1;buffer/buffs_page
java.lang.NullPointerException
        at org.l2j.scripts/handlers.communityboard.HomeBoard.parseCommunityBoardCommand(HomeBoard.java:297)
        at org.l2j.gameserver/org.l2j.gameserver.handler.CommunityBoardHandler.handleParseCommand(CommunityBoardHandler.java:98)
        at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.RequestBypassToServer.runImpl(RequestBypassToServer.java:120)
        at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:36)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)
        at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$1.run(PriorityThreadFactory.java:30)
[WARN ][2020-06-09 10:02:01][RequestBypassToServer:runImpl:220]: [Player: AA[39574] - Account: singto01 - IP: 124.122.238.178] sent not handled RequestBypa
ssToServer: [_bbsheal;buffer/buffs_page]
[WARN ][2020-06-09 10:02:12][RequestBypassToServer:runImpl:220]: [Player: AA[39574] - Account: singto01 - IP: 124.122.238.178] sent not handled RequestBypa
ssToServer: [_bbsheal;buffer/buffs_page]
[ERROR][2020-06-09 10:02:54][Client:write:100]: null
java.nio.BufferOverflowException
        at java.base/java.nio.DirectByteBuffer.put(DirectByteBuffer.java:457)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Connection.write(Connection.java:50)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.encryptAndWrite(Client.java:114)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.write(Client.java:98)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.tryWriteNextPacket(Client.java:75)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.Client.finishWriting(Client.java:155)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WriteHandler.completed(WriteHandler.java:30)
        at io.github.joealisson.mmocore/io.github.joealisson.mmocore.WriteHandler.completed(WriteHandler.java:12)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:127)
        at java.base/sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:282)
        at java.base/sun.nio.ch.WindowsAsynchronousSocketChannelImpl$WriteTask.completed(WindowsAsynchronousSocketChannelImpl.java:835)
        at java.base/sun.nio.ch.Iocp$EventHandlerTask.run(Iocp.java:387)
        at java.base/sun.nio.ch.AsynchronousChannelGroupImpl$1.run(AsynchronousChannelGroupImpl.java:112)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

**### LineageII Crash Report**
Error: AutoPotionSubWnd Transient.AutoPotionSubWnd (Function Interface.AutoPotionSubWnd.syncInventory:0001) Runaway loop detected (over 10000000 iterations)

Protocol: S_EX_BLOODY_COIN_COUNT(13, 0) <= S_EX_USER_INFO_INVENWEIGHT(17, 0) <= S_EX_ADENA_INVEN_COUNT(15, 0) <= S_EX_QUEST_ITEMLIST(16, 0) <= S_EX_QUEST_ITEMLIST(14, 0) <= S_ITEMLIST(276, 0) <= S_ITEMLIST(12, 0) <= C_ITEMLIST(3, 1) <= C_MOVE_TO_LOCATION(31, 161) <= C_MOVE_TO_LOCATION(31, 176)

History: FFrame::Serialize <- UObject::ProcessEvent <+ (AutoPotionSubWnd Transient.AutoPotionSubWnd, Function Interface.AutoPotionSubWnd.OnEvent, 0x1508A710, 0x0019E320, 16, 16) <- XMLUIManager::ExecuteUIEvent <+ ID:2600 <- ExecuteUIEvent <- NConsoleWnd::AddInventoryItem <- Handler_ExQuestItemListPacket::DisassembleItems <- PackageItemHandler::DisassembleCount <- PackageItemManager::DisassembleCount <- ExQuestItemListPacket <- ClientCmdEx <+ size:11, disassem:6767165 <- UNetworkHandler::Tick <+ Protocol Name=S_EX_QUEST_ITEMLIST <- UGameEngine::Tick <- UpdateWorld <- CMainLoop::UpdateTheWorld <- MainLoop

**Comment by vicochips** [comment]
Custom community board ?

**Comment by bahamus20** [comment]
yes

**Comment by bahamus20** [comment]
> Custom community board ?

yes
