### ISSUE TITLE
MUltiproff

### ISSUE THREAD

**Issue by u4i** [JoeAlisson/L2jOrg#427]
HOw to on multiproff?
NO optionc gservere configs

**Comment by vicochips** [comment]
Hello,

I don't understand the question.

Can you explain it again plz ?

**Comment by u4i** [comment]
I can't find the option responsible for the multi-profession so that all races and classes can learn other people's skills

**Comment by u4i** [comment]
[WARN ][2020-09-17 09:58:58][1][EventScheduler:run:152]: null
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.l2j.gameserver/org.l2j.gameserver.model.eventengine.EventMethodNotification.execute(EventMethodNotification.java:51)
        at org.l2j.gameserver/org.l2j.gameserver.model.eventengine.EventScheduler.run(EventScheduler.java:149)
        at org.l2j.gameserver/org.l2j.gameserver.model.eventengine.conditions.HaventRunConditionalScheduler.run(HaventRunConditionalScheduler.java:63)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at org.l2j.gameserver/org.l2j.gameserver.model.eventengine.AbstractEventManager.startConditionalSchedulers(AbstractEventManager.java:80)
        at org.l2j.gameserver/org.l2j.gameserver.engine.events.EventEngine.parseEvent(EventEngine.java:106)
        at org.l2j.commons/org.l2j.commons.xml.XmlReader.forEach(XmlReader.java:181)
        at org.l2j.commons/org.l2j.commons.xml.XmlReader.forEach(XmlReader.java:167)
        at org.l2j.gameserver/org.l2j.gameserver.engine.events.EventEngine.lambda$parseDocument$0(EventEngine.java:69)
        at org.l2j.commons/org.l2j.commons.xml.XmlReader.forEach(XmlReader.java:181)
        at org.l2j.commons/org.l2j.commons.xml.XmlReader.forEach(XmlReader.java:167)
        at org.l2j.gameserver/org.l2j.gameserver.engine.events.EventEngine.parseDocument(EventEngine.java:69)
        at org.l2j.commons/org.l2j.commons.xml.XmlReader.parseFile(XmlReader.java:118)
        at org.l2j.commons/org.l2j.commons.xml.XmlReader.parseDirectory(XmlReader.java:147)
        at org.l2j.gameserver/org.l2j.gameserver.util.GameXmlReader.parseDatapackDirectory(GameXmlReader.java:63)
        at org.l2j.gameserver/org.l2j.gameserver.engine.events.EventEngine.load(EventEngine.java:63)
        at org.l2j.gameserver/org.l2j.gameserver.engine.events.EventEngine.init(EventEngine.java:164)
        at org.l2j.gameserver/org.l2j.gameserver.GameServer.<init>(GameServer.java:196)
        at org.l2j.gameserver/org.l2j.gameserver.GameServer.main(GameServer.java:269)
Caused by: java.lang.reflect.UndeclaredThrowableException
        at com.sun.proxy.$Proxy70.updateSnapshot(Unknown Source)
        at org.l2j.gameserver/org.l2j.gameserver.engine.rank.RankEngine.updateDatabase(RankEngine.java:186)
        at org.l2j.gameserver/org.l2j.gameserver.engine.rank.RankEngine.updateRankers(RankEngine.java:129)
        at org.l2j.gameserver/org.l2j.gameserver.instancemanager.DailyTaskManager.onReset(DailyTaskManager.java:85)
        ... 32 more

**Comment by u4i** [comment]
how fix?

**Comment by vicochips** [comment]
I don't think there is an option for this

**Comment by u4i** [comment]
I don't think there is an option for this --- ok plise tell how i can activate multi proff options.    (warning im fix)

**Comment by vicochips** [comment]
There is no option for multi proff I think^^

**Comment by Forcecat01** [comment]
take pages **skillTrees** and do what you want including multiprofessions
