### ISSUE TITLE
Unable to send big HTML to client

### ISSUE THREAD

**Issue by Revertron** [JoeAlisson/L2jOrg#62]
**Describe the bug**
I'm trying to enable custom community board with buffer.
The community board is showing normally, but when I try to click on the Buffer button (send about 5kb html) this exception is shown in gameserver console:
```
[ERROR][2019-05-02 18:30:10][IClientOutgoingPacket:write:114]: Error writing packet ShowBoard to client [Character: Rev[32173] - Account: rev - IP: 127.0.0.1]
[ERROR][2019-05-02 18:30:10][IClientOutgoingPacket:write:115]: null
java.nio.BufferOverflowException
        at java.base/java.nio.HeapByteBuffer.put(HeapByteBuffer.java:216)
        at java.base/java.nio.ByteBuffer.put(ByteBuffer.java:906)
        at io.github.joealisson.mmocore@2.2.1-SNAPSHOT/io.github.joealisson.mmocore.WritablePacket.writeStringWithCharset(WritablePacket.java:42)
        at io.github.joealisson.mmocore@2.2.1-SNAPSHOT/io.github.joealisson.mmocore.WritablePacket.writeString(WritablePacket.java:36)
        at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.ShowBoard.writeImpl(ShowBoard.java:46)
        at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.IClientOutgoingPacket.write(IClientOutgoingPacket.java:110)
        at org.l2j.gameserver/org.l2j.gameserver.network.serverpackets.IClientOutgoingPacket.write(IClientOutgoingPacket.java:15)
        at io.github.joealisson.mmocore@2.2.1-SNAPSHOT/io.github.joealisson.mmocore.WritablePacket.writeData(WritablePacket.java:65)
        at io.github.joealisson.mmocore@2.2.1-SNAPSHOT/io.github.joealisson.mmocore.Client.write(Client.java:86)
        at io.github.joealisson.mmocore@2.2.1-SNAPSHOT/io.github.joealisson.mmocore.Client.write(Client.java:76)
        at io.github.joealisson.mmocore@2.2.1-SNAPSHOT/io.github.joealisson.mmocore.Client.tryWriteNextPacket(Client.java:69)
        at io.github.joealisson.mmocore@2.2.1-SNAPSHOT/io.github.joealisson.mmocore.Client.writePacket(Client.java:59)
        at org.l2j.gameserver/org.l2j.gameserver.network.L2GameClient.sendPacket(L2GameClient.java:302)
        at org.l2j.gameserver/org.l2j.gameserver.model.actor.instance.L2PcInstance.sendPacket(L2PcInstance.java:3556)
        at org.l2j.gameserver/org.l2j.gameserver.util.Util.sendCBHtml(Util.java:475)
        at org.l2j.gameserver/org.l2j.gameserver.util.Util.sendCBHtml(Util.java:431)
        at org.l2j.gameserver/org.l2j.gameserver.util.Util.sendCBHtml(Util.java:417)
        at org.l2j.gameserver/org.l2j.gameserver.handler.CommunityBoardHandler.separateAndSend(CommunityBoardHandler.java:42)
        at org.l2j.scripts/handlers.communityboard.HomeBoard.parseCommunityBoardCommand(HomeBoard.java:271)
        at org.l2j.gameserver/org.l2j.gameserver.handler.CommunityBoardHandler.handleParseCommand(CommunityBoardHandler.java:108)
        at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.RequestBypassToServer.runImpl(RequestBypassToServer.java:126)
        at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.IClientIncomingPacket.run(IClientIncomingPacket.java:38)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:835)
        at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$1.run(PriorityThreadFactory.java:35)
```
I think, that there is a problem with buffer sizes, but I've tested even with big buffers - no luck.

**To Reproduce**
1. Enable custom community board
2. Click on buffer

**Expected behavior**
Packets of all shapes and sizes should get written to the client :)

**Comment by JoeAlisson** [comment]
The packet's size configuration work still in progress. 

But for now you can configure the Packet size on [async-mmocore.properties](https://github.com/JoeAlisson/L2jOrg/blob/master/Gameserver/src/main/resources/config/async-mmocore.properties) file

just change the following property with the size that you need
bufferDefaultSize = 8120

**Comment by lordofdest** [comment]
Possibly can affect packets like ItemList, QuestItemList, WarehouseDepositList etc.

**Comment by Revertron** [comment]
> just change the following property with the size that you need
> bufferDefaultSize = 8120

It doesn't work :(

**Comment by lordofdest** [comment]
I think method **size** in **WritablePacket** is unnecessary because easy to take a mistake, better is simulate writeImpl but may has performance issue or use max size of packet specified by protocol(20Kb).

PTS use pool of CIOBuffer`s with max size of packets this is may reduce time to query buffer from ResourcePool.

Why **Connection** and **Client** classes has only one instance of "operation buffer" w/o tracking of current position in it, what about server try to send packets simultaneously? 

Sorry for my English :)

**Comment by JoeAlisson** [comment]
> 
> It doesn't work :(

Can you provide the html and the value of bufferDefaultSize, so I can verify this problem :)

**Comment by JoeAlisson** [comment]
> I think method **size** in **WritablePacket** is unnecessary because easy to take a mistake, better is simulate writeImpl but may has performance issue or use max size of packet specified by protocol(20Kb).

I agre that size can be lead to a mistake. However I'm afraid that performance issues can cause much more problem. At Runtime can have thousands of ByteBuffers because of the mmocore's nature asynchronous, the "size" was the way that I found to try prevent OutOfMemory errors easily. But I'm very open to alternatives however I don't think the simulate writeImpl will be a better way.


> PTS use pool of CIOBuffer`s with max size of packets this is may reduce time to query buffer from ResourcePool.

Sorry I've never heard about this pool, can you point some documentation ?  :(


> Why **Connection** and **Client** classes has only one instance of "operation buffer" w/o tracking of current position in it, what about server try to send packets simultaneously?

Unfortunately the mmocore used doesn't yet support "gathering write".  So for now its only possible to send a packet at time to one client,  its only possible to send packet simultaneously to different clients.  It still on development but I want to make sure that worth to use it before add new functionalities

**Comment by lordofdest** [comment]
Sorry about max packets size is 0x2000.

I doesn't have documentation about CIOBuffer only has reverse engineered info:
#define BUFFER_SIZE 8192
class CIOBuffer{

**Comment by Revertron** [comment]
> Can you provide the html and the value of bufferDefaultSize, so I can verify this problem :)
I've tried even 8192 for bufferDefaultSize, but no luck :(
The file is this: "gameserver/data/html/CommunityBoard/Custom/buffer/main.html" from mobius's datapack.

**Comment by JoeAlisson** [comment]
This html is greater than 8K. This is because the String is represented as UTF16 so each character consumes 2 bytes, so 13312 bufferDefaultSize will be anough to this html

**Comment by JoeAlisson** [comment]
> I doesn't have documentation about CIOBuffer only has reverse engineered info:
> Buffers creates lazy when needed.
> m_pNext link to next buffer. used when user has many packets in queue.

The ResourcePool works like this, but have some limitations, it need to be improved without doubt :)

> Maybe better return 0x2000 from **size** ?
This is the actual default value when the method size is not overridden. But for some reason I did a mistake to put a bit smaller value on properties file
