### ISSUE TITLE
"rank" is restricted word in newest MySQL version

### ISSUE THREAD

**Issue by nordbit** [JoeAlisson/L2jOrg#68]
emulator version 1.3
MySQL version 8.0.17

error on console when gameserver start:
```
[ERROR][2019-08-09 17:29:58][L2Clan:restoreRankPrivs:1491]: Error restoring clan privs by rank: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ',party FROM clan_privs WHERE clan_id=33844' at line 1
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ',party FROM clan_privs WHERE clan_id=33844' at line 1
        at mysql.connector.java@8.0.16/com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at mysql.connector.java@8.0.16/com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at mysql.connector.java@8.0.16/com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at mysql.connector.java@8.0.16/com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
        at mysql.connector.java@8.0.16/com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1005)
        at com.zaxxer.hikari@3.3.1/com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
        at com.zaxxer.hikari@3.3.1/com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
        at org.l2j.gameserver/org.l2j.gameserver.model.L2Clan.restoreRankPrivs(L2Clan.java:1476)
        at org.l2j.gameserver/org.l2j.gameserver.model.L2Clan.restore(L2Clan.java:907)
        at org.l2j.gameserver/org.l2j.gameserver.model.L2Clan.<init>(L2Clan.java:154)
        at org.l2j.gameserver/org.l2j.gameserver.data.sql.impl.ClanTable.<init>(ClanTable.java:76)
        at org.l2j.gameserver/org.l2j.gameserver.data.sql.impl.ClanTable$Singleton.<clinit>(ClanTable.java:397)
        at org.l2j.gameserver/org.l2j.gameserver.data.sql.impl.ClanTable.getInstance(ClanTable.java:393)
        at org.l2j.gameserver/org.l2j.gameserver.GameServer.<init>(GameServer.java:139)
        at org.l2j.gameserver/org.l2j.gameserver.GameServer.main(GameServer.java:286)
```
Game client crashing when character with clan (leader) enter the world - it can be related or not, but new character without clan can enter the world

**Comment by nordbit** [comment]
Game client crash is not related to this issue, I changed my query, game still crashing
```
Error: Assertion failed: Location.X != 0.f || Location.Y != 0.f || Location.Z != 0 [File:L2NetNotify.cpp] [Line: 1631]

Protocol: S_ACQUIRE_SKILL_LIST(599) <= S_SKILL_LIST(1109) <= S_PLEDGE_INFO(29) <= S_EX_AUTO_SOULSHOT(17) <= S_EX_AUTO_SOULSHOT(17) <= S_EX_AUTO_SOULSHOT(17) <= S_EX_AUTO_SOULSHOT(17) <= S_EX_ONE_DAY_REWARD_INFO(53) <= S_SKILL_COOL_TIME(7) <= S_SKILL_COOL_TIME(7)

History: UGameEngine::OnUserInfo <- UIPacket_OnUserInfo_2 <+ OldPos=(0:0:0), CurPos:(0:0:0) <- Setting 2 <- UIPacket <- ClientCmd <+ size:85, disassem:8 <- UNetworkHandler::Tick <+ Protocol Name=S_USER_INFO <- UGameEngine::Tick <- UpdateWorld <- CMainLoop::UpdateTheWorld <- MainLoop
```
Character is Elf, own clan leader who win auction on clan hall, sps weared in Avadon and Wizzards Tears Acumen, not related to world position (I changed character location in DB to 100% safe, occupied by another character who can log without problem ). No idea what is wrong. Soulshots? Skill? Obviously with character update on enter world

**Comment by JoeAlisson** [comment]
@nordbit Can you try the latest on branch development ? I'm quite sure that this issue was already fixed

**Comment by nordbit** [comment]
I can't. Branch development is compiling well, but on cosole got error:
```
Exception in thread "main" java.lang.IllegalAccessError: class io.github.joealisson.primitive.CHashIntMap (in module io.github.joealisson.primitive) cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to module io.github.joealisson.primitive
        at io.github.joealisson.primitive/io.github.joealisson.primitive.CHashIntMap.<clinit>(CHashIntMap.java:6399)
        at org.l2j.authserver/org.l2j.authserver.controller.GameServerManager.<init>(GameServerManager.java:32)
        at org.l2j.authserver/org.l2j.authserver.controller.GameServerManager$Singleton.<clinit>(GameServerManager.java:136)
        at org.l2j.authserver/org.l2j.authserver.controller.GameServerManager.getInstance(GameServerManager.java:128)
        at org.l2j.authserver/org.l2j.authserver.AuthServer.<init>(AuthServer.java:37)
        at org.l2j.authserver/org.l2j.authserver.AuthServer.main(AuthServer.java:65)
```
Custom modules in version:
async-mmocore-3.0.0-SNAPSHOT.jar
primitive-2.0.0-SNAPSHOT.jar

**Comment by JoeAlisson** [comment]
The next release will need to run java with the "--add-exports java.base/jdk.internal.misc=io.github.joealisson.primitive" option for awhile. So to run the next release the command will be:

`java --enable-preview -Dfile.encoding=UTF-8 -Xms512m -Xmx2g -p ./lib -cp config;./lib/* --add-exports java.base/jdk.internal.misc=io.github.joealisson.primitive -m org.l2j.gameserver/org.l2j.gameserver.GameServer `

**Comment by nordbit** [comment]
```
[WARN ][2019-08-11 15:49:51][accounting:runImpl:27]: Wrong protocol version 166, [IP: 127.0.0.1]
```

Client disconnected

**Comment by JoeAlisson** [comment]
Please, verify in your server.properties file
`AllowedProtocolRevisions = 166`

**Comment by nordbit** [comment]
My fault,  I didn't copy new config files.
Another error:
```
Caused by: java.sql.SQLSyntaxErrorException: Table 'l2jorg.character_relationship' doesn't exist
```
I can't find sql in datapack named 'character_relationship.sql' ?

**Comment by JoeAlisson** [comment]
I didn't rename the file yet :)

https://github.com/JoeAlisson/L2jOrg/blob/development/Datapack/gameserver/sql/install/character_friends.sql

**Comment by nordbit** [comment]
```
[INFO ][2019-08-11 16:44:14][accounting:runImpl:125]: [Character: Lily[33819] - Account: jancio - IP: 127.0.0.1] Logged in
```
:D
