### ISSUE TITLE
clan_privs and REQUEST_USER_BAN_INFO

### ISSUE THREAD

**Issue by Forcecat01** [JoeAlisson/L2jOrg#69]
Hi, tell me pls how to fix this.

`[WARN ][2019-09-01 03:17:43][L2Clan:setRankPrivs:1519]: Could not store clan privs for rank: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank,party,privs) VALUES (33835,1,0,2) ON DUPLICATE KEY UPDATE privs = 2' at line 1
java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'rank,party,privs) VALUES (33835,1,0,2) ON DUPLICATE KEY UPDATE privs = 2' at line 1
	at mysql.connector.java@8.0.16/com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at mysql.connector.java@8.0.16/com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at mysql.connector.java@8.0.16/com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at mysql.connector.java@8.0.16/com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:955)
	at mysql.connector.java@8.0.16/com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:372)
	at com.zaxxer.hikari@3.3.1/com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari@3.3.1/com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.l2j.gameserver/org.l2j.gameserver.model.L2Clan.setRankPrivs(L2Clan.java:1517)
	at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.RequestPledgePower.runImpl(RequestPledgePower.java:43)
	at org.l2j.gameserver/org.l2j.gameserver.network.clientpackets.ClientPacket.run(ClientPacket.java:36)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
	at org.l2j.commons/org.l2j.commons.threading.PriorityThreadFactory$1.run(PriorityThreadFactory.java:35)`

The error appears after I try to set privileges in the clan

and this mistake. which package am i using? why could there be a WARN?

`WARN ][2019-09-01 03:17:14][ClientPacketHandler:unknownPacket:54]: Unknown Packet (REQUEST_USER_BAN_INFO) : d0 - 00000000 D05F0129840000                   ._.)...
`

**Comment by JoeAlisson** [comment]
This Issue was already reported on  #68 and fixed.

About the Warn message, There are some no implemented packets so this Warn is there to remember me to implement. You can configure your log4j.xml to not show these warn messages.
